### ISSUE TITLE
quick-fix laundry list

### ISSUE THREAD

**Issue by bhs** [lightstep/lightstep-tracer-ruby#23]
#22 is/was awesome, but there are some loose ends:

- [x] The README is out-of-date re installation instructions
- [x] The `Makefile` doesn't do `bundle rake ...` and thus is broken / non-hermetic

**Comment by ngauthier** [comment]
Will do this AM.

**Comment by ngauthier** [comment]
Looks like you already fixed the makefile. Sending PR on the README...
