### ISSUE TITLE
Lightstep treats Spans SpanContexts differently from OpenTracing specs

### ISSUE THREAD

**Issue by nanzhong** [lightstep/lightstep-tracer-ruby#48]
I've been attempting to use lightstep and noticed that the current implementation's handling of `Span`s and `SpanContext`s is not consistent with the OpenTracing specs.

In particular, looking at the specs it seems that `Tracer#start_span`, `Tracer#inject`, and `Tracer#extract` should be taking/returning `SpanContext`s instead of `Span`s. I noticed this after seeing a crash using the noop ruby OpenTracing implementation, since `Tracer#extract` is defined to return a `SpanContext` instead of a `Span`, which the lightstep implementation does.

I'd be happy to implement the changes needed to be consistent, but wanted to double check and see if this was intentionally done this way or whether it's just because the ruby lightstep gem predates the OpenTracing spec.

**Comment by iredelmeier** [comment]
Looks like this was fixed by [#2b875d2](https://github.com/lightstep/lightstep-tracer-ruby/commit/2b875d2). Happy to reopen if you're still seeing problems.
