### ISSUE TITLE
Issue in initializing the light step

### ISSUE THREAD

**Issue by ghost** [lightstep/lightstep-tracer-ruby#60]
I am getting the following error.
Looks like  initializer file is not being loaded at all.   
**Message from application: /usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:29: syntax error, unexpected ','**
Lightstep version is lightstep (0.10.9, 0.10.7)
Ruby version: ruby 2.0.0p648
Rails version: Rails 3.2.9

The initializer file(config/initializer/lightstep.rb) class looks like:

**require 'lightstep'
component_name = 'demand-engine-' + ENV['RAILS_ENV']
token = ENV['LIGHTSTEP_ACCESS_TOKEN']
collector_host = ENV['LIGHTSTEP_COLLECTOR_HOST']
collector_port = ENV['LIGHTSTEP_COLLECTOR_PORT'].to_i
LightStep.configure(component_name: component_name, access_token: token)** 

Please help me.

The full error trace is:

Message from application: /usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:29: syntax error, unexpected ','
...def initialize(component_name:, access_token: nil, transport...
...                               ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:29: Can't assign to nil
...onent_name:, access_token: nil, transport: nil, tags: {})
...                               ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:29: Can't assign to nil
...ess_token: nil, transport: nil, tags: {})
...                               ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:162: syntax error, unexpected ','
... def configure(component_name:, access_token: nil, transport...
...                               ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:162: Can't assign to nil
...onent_name:, access_token: nil, transport: nil, tags: {})
...                               ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:162: Can't assign to nil
...ess_token: nil, transport: nil, tags: {})
...                               ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:183: dynamic constant assignment
    CARRIER_TRACER_STATE_PREFIX = 'ot-tracer-'.freeze
                                 ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:184: dynamic constant assignment
    CARRIER_BAGGAGE_PREFIX = 'ot-baggage-'.freeze
                            ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:186: dynamic constant assignment
    CARRIER_SPAN_ID = (CARRIER_TRACER_STATE_PREFIX + 'spanid').freeze
                     ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:187: dynamic constant assignment
    CARRIER_TRACE_ID = (CARRIER_TRACER_STATE_PREFIX...
                      ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:188: dynamic constant assignment
    CARRIER_SAMPLED = (CARRIER_TRACER_STATE_PREFIX + 'sampled').freeze
                     ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:190: dynamic constant assignment
    DEFAULT_MAX_LOG_RECORDS = 1000
                             ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:191: dynamic constant assignment
    MIN_MAX_LOG_RECORDS = 1
                         ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:192: dynamic constant assignment
    DEFAULT_MAX_SPAN_RECORDS = 1000
                              ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:193: dynamic constant assignment
    MIN_MAX_SPAN_RECORDS = 1
                          ^
/usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep/tracer.rb:257: syntax error, unexpected keyword_end, expecting end-of-input (SyntaxError)
  /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
  /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `block in require'
  /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
  /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
  /usr/local/lib/ruby/gems/2.0.0/gems/lightstep-0.10.9/lib/lightstep.rb:37:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
  /home/omjaiswal/kp_demand_engine1/config/application.rb:7:in `<top (required)>'
  /home/omjaiswal/kp_demand_engine1/config/environment.rb:2:in `require'
  /home/omjaiswal/kp_demand_engine1/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/local/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /usr/local/lib/ruby/gems/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:107:in `eval'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:107:in `preload_app'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:153:in `<module:App>'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-5.0.10/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by tedsuo** [comment]
Hi @OPJay,

The lightstep ruby tracer is tested against the supported versions of ruby, the oldest of which is `ruby 2.2.7`. The tracer currently uses required keyword arguments, a feature that was added in `2.1`, which is why you are receiving that error. Sorry that this is not documented.

We can look at `2.0` support if necessary. However, I highly recommend moving to a supported ruby version if you can, as they no longer issue security patches for 2.0.

BTW, in a separate thread you mentioned you had it working in `1.9.3p484`. That is very surprising to me! I have not been able to recreate this. Can you confirm?

Thanks,
-Ted

**Comment by ghost** [comment]
Hi Ted,

Surprisingly it  was working on 1.9.3p484 , until i did bundle install which screwed things up.
I couldn't resolve the errors after that.
i was wondering how it was working without linking the host and port.
It was done in a older fashion as mentioned in the README file.
Upgrading to 2.2.7 version or newer will be troublesome for us we are running 2.1.9p490 on prod itself.
Please suggest some workaround to get it running in prod.
The older way without using Tracer that working has following changes.

In initializer 👍 
**require 'lightstep'
component_name = 'demand-engine-' + ENV['RAILS_ENV']
token = ENV['LIGHTSTEP_ACCESS_TOKEN']
collector_host = ENV['LIGHTSTEP_COLLECTOR_HOST']
collector_port = ENV['LIGHTSTEP_COLLECTOR_PORT'].to_i
LightStep.configure(component_name: component_name, access_token: token)** 

In controller class we used:

**span = LightStep.start_span('my_span')
span.log(event: 'hello world', count: 42)
//some implementation
child = LightStep.start_span('my_child', child_of: span.span_context)
//another implementation
child.finish
sleep(0.1)
span.finish**

Regards,
Om

**Comment by tedsuo** [comment]
Hi @OPJay, our tracer should work as is with `2.1.9p490`. The feature that is causing it to break, "required keyword arguments", was added in `2.1`. So it should work as-is if `2.1` is an acceptable version for you. I understand how much effort it can be to upgrade your ruby version, so let me know if that works.

I wonder if you were using a very old version of the tracer on 1.9.3, I can't come up with a way it would not break on keyword arguments otherwise.

To answer your setup question, `Lightstep.configure` creates the global tracer, and takes the same options as a Tracer. 

```ruby
Lightstep.configure(
    component_name: 'lightstep/ruby/example',
    transport: LightStep::Transport::HTTPJSON.new(
      host: 'localhost',
      port: 8000,
      access_token: 'MY_ACCESS_TOKEN'
    )
)
```

If you do not pass in a transport, the tracer will connect to our public collectors by default, which is why it was working without the host and port configured. Public collectors work but are not what you want for production, you'll want the co-located collectors for that.

**Comment by ghost** [comment]
Hi Ted,
On stage this is what works for us.It doesn't work on prod though.
**LightStep.configure(component_name: component_name, access_token: token)**
While following doesn't work anywhere for some reason.
**Lightstep.configure(
    component_name: component_name,
    transport: LightStep::Transport::HTTPJSON.new(
        host: collector_host,
        port: collector_port,
        access_token: token
    )
)**

Please tell if i am missing something again.
Regards,
Om

**Comment by tedsuo** [comment]
Sorry to hear that @OPJay,

- What version of the tracer are you using?
- What version of ruby?
- Can you provide the error output trace?

BTW you can see tracer initialization here: https://github.com/lightstep/lightstep-tracer-ruby/blob/0.11.2/lib/lightstep/tracer.rb#L150

And transport initialization here: https://github.com/lightstep/lightstep-tracer-ruby/blob/0.11.2/lib/lightstep/transport/http_json.rb#L27

**Comment by ghost** [comment]
Hi Ted, 
the actual issue is non gprc collection hosts are not working for ruby
@host="collector.lightstep.com works and  @host="collector-no-gprc.lightstep.com  doesn't work.
It was recommended that no-gprc host should be used. Can you tell why is it not working?

**Comment by iredelmeier** [comment]
Closing for now since the issue has gotten stale. Happy to reopen if you're still having issues, @OPJay!
