### ISSUE TITLE
Span tag values that are not strings cause the span to not be recorded

### ISSUE THREAD

**Issue by ethanjcohen-underarmour** [lightstep/lightstep-tracer-ruby#70]
I noticed that `set_tag` converts the value to a string:
https://github.com/lightstep/lightstep-tracer-ruby/blob/master/lib/lightstep/span.rb#L69

But the values passed in an object of tags to `start_span` never get converted to strings.
https://github.com/lightstep/lightstep-tracer-ruby/blob/master/lib/lightstep/span.rb#L45

For example, this library saves a bool and number to tags, which does not seem to work unless I add `.to_s` to both values:
https://github.com/iaintshine/ruby-rails-tracer/blob/master/lib/rails/active_record/tracer.rb#L57

The opentracing spec says that bools and numeric types are allowed:
https://github.com/opentracing/specification/blob/master/specification.md#set-a-span-tag

**Comment by austinlparker** [comment]
Thanks for opening this issue! It does seem like we're missing some coercion to string when values get added through `start_span`. I'll see if we can get a fix out soonish.

**Comment by ethanjcohen-underarmour** [comment]
@austinlparker Does lightstep only accept strings? Is that why we need to coerce bools and numbers?

**Comment by austinlparker** [comment]
No, we accept more than strings, so I'm actually surprised that this isn't working. I need to do some more research to understand why the problem is happening, but we should be able to get a fix out in the short term.

**Comment by austinlparker** [comment]
Looked into this a bit more and it seems like the Ruby tracer is still on an old API endpoint. We've got some stuff in-flight to move it over to a newer reporting method, but that work isn't done yet.

**Comment by ethanjcohen-underarmour** [comment]
Meaning that this is expected with the old API and will be fixed when you point the tracer to the new API? or you're not sure?

**Comment by austinlparker** [comment]
Yes, it's expected with the old API. I've got a PR in right now that fixes this temporarily (by replicating the behavior of `set_tag` when adding tags on building spans and coercing values to strings) but will eventually change to allow span tags to be numbers, booleans, etc.

**Comment by ethanjcohen-underarmour** [comment]
Perfect, thanks for the quick response!
