### ISSUE TITLE
Support OT Gem 0.5.0

### ISSUE THREAD

**Issue by austinlparker** [lightstep/lightstep-tracer-ruby#79]
Need to update to support the most recently released version of the OT Gem (https://rubygems.org/gems/opentracing/versions/0.5.0)

**Comment by josh-lauer** [comment]
What are the prospects of this happening? I could really use it.

**Comment by austinlparker** [comment]
Let me check and see if we've got anyone free to do this internally.

**Comment by austinlparker** [comment]
released in 0.15.0
